# ===== PRODUCTION =====

nasa.api.key=${NASA_API_KEY}
nasa.jwt.secret=${JWT_SECRET}
nasa.jwt.expiration=3600000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:5000}