# ===== DOCKER =====

nasa.api.key=LYGMcV3NWOfFSTHi7SsbPHUWb9c1ZZYTN6VLDJrt
nasa.jwt.secret=nasa_vault_super_secure_jwt_secret_2026_x7K91LmP
nasa.jwt.expiration=3600000

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/nasa-directory
spring.datasource.username=root
spring.datasource.password=Sachin12#

spring.jpa.hibernate.ddl-auto=update

server.port=5000